idci_contactform:
    mode:               normal  # "normal"      Store transiting messages
                                # "anonyme"     Do not keep transiting messages content and origin
                                # "social"      Store transiting messages and allow the bundle to serve them throw an api (need idci-exporter-bundle)

    tracking_enabled:   true    # Keep for all messages the ip, the user-agent and the referer
    https_only:         false   # Work only with https request
    restricted_method:  ANY     # Available choices: POST | PUT | GET