TODO
=====

mode:
    normal (Store transiting messages)
    anonyme(do not keep transiting messages content and origin)
    social:(Store transiting messages and allow the bundle to serve them throw an api (need idci-exporter-bundle)

security:
    tracking_enabled: boolean (keep for all message the ip, the user-agent and the referer)
    https_only: boolean
    method_get_only: boolean
    method_post_only: boolean
