services:
    idci_contactform.type.text_coma_separated_values:
        class: IDCI\Bundle\ContactFormBundle\Form\Type\TextComaSeparatedValuesType
        tags:
            - { name: form.type, alias: text_coma_separated_values }

    idci_contactform.manager:
        class: IDCI\Bundle\ContactFormBundle\Service\Manager
        arguments: [@service_container]

    idci_contactform.provider.mailer:
        class: IDCI\Bundle\ContactFormBundle\Provider\MailerProvider
        arguments: [@mailer]

    idci_contactform.provider.social_sharer:
        class: IDCI\Bundle\ContactFormBundle\Provider\SocialSharerProvider
